---
title: "Descriptive Modeling on Home Prices"
author: "Boni M. Ale, MD, MSc, MPH"
date: "2023-03-07"
output: html_document
---

```{r loading packages}

pacman::p_load(
  readr,
  dplyr,
  janitor,
  here,
  ggplot2,
  Hmisc
  #AmesHousing
)
```

```{r data loading}
ames_raw <- as_tibble(read_csv(
  here("Ames_HousePrice.csv")
)) 

ames_geo_raw <- as_tibble(read_csv(
  here("Ames_Real_Estate_Data.csv")
))

```


```{r data processing}
ten_point <- c(
  "Very_Excellent",
  "Excellent",
  "Very_Good",
  "Good",
  "Above_Average",
  "Average",
  "Below_Average",
  "Fair",
  "Poor",
  "Very_Poor"
)

five_point <- c(
  "Excellent",
  "Good",
  "Typical",
  "Fair",
  "Poor"
)

## create a pid variable in ames_geo 

ames_geo_modif <- ames_geo_raw %>% 
  janitor::clean_names() %>%
  dplyr::mutate(
    pid = as.numeric(map_ref_no)
  ) %>% 
  dplyr::select(
    - neighborhood
  )
  

## calculate the amount of missing data in year garage was built
prop.table(table(is.na(ames_raw$GarageYrBlt)))*100

## process ames_raw data

process_ames <- ames_raw %>%
  janitor::clean_names() %>% 
    # # Rename variables with spaces or begin with numbers
    # # SalePrice would be inconsistently named so change that too.
    # dplyr::rename_with(
    #   ~ gsub(' ', '_', .),
    #   dplyr::contains(' '),
    # ) %>%
    # dplyr::rename(
    #   Sale_Price = SalePrice,
    #   Three_season_porch = `3SsnPorch`,
    #   Year_Remod_Add = `YearRemodAdd`,
    #   First_Flr_SF = `1stFlrSF`,
    #   Second_Flr_SF = `2ndFlrSF`,
    #   Year_Sold = YrSold
    # ) %>%

    # transform to factors levels
    dplyr::mutate(
      ms_sub_class = as.character(as.integer(ms_sub_class))
    ) %>%
    # Make more meaningful factor levels for some variables
    dplyr::mutate(
      ms_sub_class =
        dplyr::recode_factor(
          factor(ms_sub_class),
          '20' = 'One_Story_1946_and_Newer_All_Styles',
          '30' = 'One_Story_1945_and_Older',
          '40' = 'One_Story_with_Finished_Attic_All_Ages',
          '45' = 'One_and_Half_Story_Unfinished_All_Ages',
          '50' = 'One_and_Half_Story_Finished_All_Ages',
          '60' = 'Two_Story_1946_and_Newer',
          '70' = 'Two_Story_1945_and_Older',
          '75' = 'Two_and_Half_Story_All_Ages',
          '80' = 'Split_or_Multilevel',
          '85' = 'Split_Foyer',
          '90' = 'Duplex_All_Styles_and_Ages',
          '120' = 'One_Story_PUD_1946_and_Newer',
          '150' = 'One_and_Half_Story_PUD_All_Ages',
          '160' = 'Two_Story_PUD_1946_and_Newer',
          '180' = 'PUD_Multilevel_Split_Level_Foyer',
          '190' = 'Two_Family_conversion_All_Styles_and_Ages'
        )
    ) %>%
    dplyr::mutate(
      ms_zoning =
        dplyr::recode_factor(
          factor(ms_zoning),
          'A' = 'Agriculture',
          'C' = 'Commercial',
          'FV' = 'Floating_Village_Residential',
          'I' = 'Industrial',
          'RH' = 'Residential_High_Density',
          'RL' = 'Residential_Low_Density',
          'RP' = 'Residential_Low_Density_Park',
          'RM' = 'Residential_Medium_Density',
          'A (agr)' = 'A_agr',
          'C (all)' = 'C_all',
          'I (all)' = 'I_all'
        )
    ) %>%
    dplyr::mutate(
      lot_shape =
        dplyr::recode_factor(
          factor(lot_shape),
          'Reg' = 'Regular',
          'IR1' = 'Slightly_Irregular',
          'IR2' = 'Moderately_Irregular',
          'IR3' = 'Irregular'
        )
    ) %>%
    dplyr::mutate(bldg_type =
                    dplyr::recode_factor(factor(bldg_type),
                                         '1Fam' = 'OneFam',
                                         '2fmCon' = 'TwoFmCon')) %>%
    # Change some factor levels so that they make valid R variable names
    dplyr::mutate(
      house_style =  gsub("^1.5", "One_and_Half_", house_style),
      house_style =  gsub("^1", "One_", house_style),
      house_style =  gsub("^2.5", "Two_and_Half_", house_style),
      house_style =  gsub("^2", "Two_", house_style),
      house_style = factor(house_style)
    ) %>%
    # Some characteristics that houses lack (e.g. garage, pool) are
    # coded as missing instead of "No_pool" or "No_Garage". Change these
    # and also cases where the number of missing (e.g. garage size)
    dplyr::mutate(
      bsmt_exposure = ifelse(is.na(bsmt_exposure), "No_Basement", bsmt_exposure),
      bsmt_exposure = factor(bsmt_exposure),
      bsmt_fin_type1 = ifelse(is.na(bsmt_fin_type1), "No_Basement", bsmt_fin_type1),
      bsmt_fin_type1 = factor(bsmt_fin_type1),
      bsmt_fin_sf1 = ifelse(is.na(bsmt_fin_sf1), 0, bsmt_fin_type1),
      bsmt_fin_type2 = ifelse(is.na(bsmt_fin_type2), "No_Basement", bsmt_fin_type2),
      bsmt_fin_type2 = factor(bsmt_fin_type2),
     bsmt_fin_sf2 = ifelse(is.na( bsmt_fin_sf2), 0,bsmt_fin_sf2),
    bsmt_unf_sf = ifelse(is.na(bsmt_unf_sf), 0,bsmt_unf_sf),
      total_bsmt_sf = ifelse(is.na(total_bsmt_sf), 0, total_bsmt_sf),
     bsmt_full_bath = ifelse(is.na(bsmt_full_bath), 0,bsmt_full_bath),
      bsmt_half_bath = ifelse(is.na(bsmt_half_bath), 0, bsmt_half_bath),
      electrical = ifelse(is.na(electrical), "Unknown", electrical),
    ) %>%
    dplyr::mutate(garage_type =
                    dplyr::recode(garage_type,
                                  '2Types' = 'More_Than_Two_Types')) %>%
    dplyr::mutate(
      garage_type = ifelse(is.na(garage_type), "No_Garage", garage_type),
      garage_finish = ifelse(is.na(garage_finish), "No_Garage", garage_finish),
     garage_cars = ifelse(is.na(garage_cars), 0,garage_cars),
      garage_area = ifelse(is.na(garage_area), 0, garage_area),
     bsmt_full_bath = ifelse(is.na(bsmt_full_bath), 0,bsmt_full_bath),
      bsmt_half_bath = ifelse(is.na(bsmt_half_bath), 0, bsmt_half_bath),
      misc_feature = ifelse(is.na(misc_feature), "None", misc_feature),
      mas_vnr_type = ifelse(is.na(mas_vnr_type), "None", mas_vnr_type),
      mas_vnr_area = ifelse(is.na(mas_vnr_area), 0, mas_vnr_area),
      lot_frontage = ifelse(is.na(lot_frontage), 0, lot_frontage)
    ) %>%
    mutate(
      overall_qual =
        dplyr::recode(
          overall_qual,
          `10` = "Very_Excellent",
          `9` = "Excellent",
          `8` = "Very_Good",
          `7` = "Good",
          `6` = "Above_Average",
          `5` = "Average",
          `4` = "Below_Average",
          `3` = "Fair",
          `2` = "Poor",
          `1` = "Very_Poor"
        )
    ) %>%
    mutate(
      overall_cond =
        dplyr::recode(
          overall_cond,
          `10` = "Very_Excellent",
          `9` = "Excellent",
          `8` = "Very_Good",
          `7` = "Good",
          `6` = "Above_Average",
          `5` = "Average",
          `4` = "Below_Average",
          `3` = "Fair",
          `2` = "Poor",
          `1` = "Very_Poor"
        )
    ) %>%
    mutate(
      exter_qual =
        dplyr::recode(
          exter_qual,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor"
        )
    ) %>%
    mutate(
     exter_cond =
        dplyr::recode(
         exter_cond,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor"
        )
    ) %>%
    mutate(
      bsmt_qual =
        dplyr::recode(
          bsmt_qual,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor",
          .missing = "No_Basement"
        )
    ) %>%
    mutate(
     bsmt_cond =
        dplyr::recode(
         bsmt_cond,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor",
          .missing = "No_Basement"
        )
    ) %>%
    mutate(
      heating_qc =
        dplyr::recode(
          heating_qc,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor"
        )
    ) %>%
    mutate(
     kitchen_qual =
        dplyr::recode(
         kitchen_qual,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor"
        )
    ) %>%
    mutate(
     fireplace_qu =
        dplyr::recode(
         fireplace_qu,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor",
          .missing = "No_Fireplace"
        )
    ) %>%
    mutate(
      garage_qual =
        dplyr::recode(
          garage_qual,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor",
          .missing = "No_Garage"
        )
    ) %>%
    mutate(
      garage_cond =
        dplyr::recode(
          garage_cond,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor",
          .missing = "No_Garage"
        )
    ) %>%
    mutate(
     pool_qc =
        dplyr::recode(
         pool_qc,
          "Ex" = "Excellent",
          "Gd" = "Good",
          "TA" = "Typical",
          "Fa" = "Fair",
          "Po" = "Poor",
          .missing = "No_Pool"
        )
    ) %>%
    mutate(
      neighborhood =
        dplyr::recode(
          neighborhood,
          "Blmngtn" = "Bloomington_Heights",
          "Bluestem" = "Bluestem",
          "BrDale" = "Briardale",
          "BrkSide" = "Brookside",
          "ClearCr" = "Clear_Creek",
          "CollgCr" = "College_Creek",
          "Crawfor" = "Crawford",
          "Edwards" = "Edwards",
          "Gilbert" = "Gilbert",
          "Greens" = "Greens",
          "GrnHill" = "Green_Hills",
          "IDOTRR" = "Iowa_DOT_and_Rail_Road",
          "Landmrk" = "Landmark",
          "MeadowV" = "Meadow_Village",
          "Mitchel" = "Mitchell",
          "NAmes" = "North_Ames",
          "NoRidge" = "Northridge",
          "NPkVill" = "Northpark_Villa",
          "NridgHt" = "Northridge_Heights",
          "NWAmes" = "Northwest_Ames",
          "OldTown" = "Old_Town",
          "SWISU" = "South_and_West_of_Iowa_State_University",
          "Sawyer" = "Sawyer",
          "SawyerW" = "Sawyer_West",
          "Somerst" = "Somerset",
          "StoneBr" = "Stone_Brook",
          "Timber" = "Timberland",
          "Veenker" = "Veenker",
          "Hayden Lake" = "Hayden_Lake"
        )
    ) %>%
    mutate(
      alley =
        dplyr::recode(
          alley,
          "Grvl" = "Gravel",
          "Pave" = "Paved",
          .missing = "No_Alley_Access"
        )
    ) %>%
    mutate(
      paved_drive =
        dplyr::recode(
          paved_drive,
          "Y" = "Paved",
          "P" = "Partial_Pavement",
          "N" = "Dirt_Gravel"
        )
    )   %>%
    mutate(
      fence =
        dplyr::recode(
          fence,
          "GdPrv" = "Good_Privacy",
          "MnPrv" = "Minimum_Privacy",
          "GdWo" = "Good_Wood",
          "MnWw" = "Minimum_Wood_Wire",
          .missing = "No_fence"
        )
    )   %>%
    # Convert everything else to factors
    dplyr::mutate(
      alley = factor(alley),
      bsmt_qual = factor(bsmt_qual),
     bsmt_cond = factor(bsmt_cond),
      central_air = factor(central_air),
      condition1 = factor(condition1),
      condition2 = factor(condition2),
      electrical = factor(electrical),
     exter_cond = factor(exter_cond),
      exter_qual = factor(exter_qual),
      exterior1st = factor(exterior1st),
      exterior2nd = factor(exterior2nd),
      fence = factor(fence),
     fireplace_qu = factor(fireplace_qu),
      foundation = factor(foundation),
      functional = factor(functional),
      garage_cond = factor(garage_cond),
      garage_finish = factor(garage_finish),
      garage_qual = factor(garage_qual),
      garage_type = factor(garage_type),
      heating = factor(heating),
      heating_qc = factor(heating_qc),
     kitchen_qual = factor(kitchen_qual),
      land_contour = factor(land_contour),
    land_slope = factor(land_slope),
      lot_config = factor(lot_config),
      mas_vnr_type = factor(mas_vnr_type),
      misc_feature = factor(misc_feature),
      paved_drive = factor(paved_drive),
     pool_qc = factor(pool_qc),
      roof_matl = factor(roof_matl),
      roof_style = factor(roof_style),
    sale_condition = factor(sale_condition),
      sale_type = factor(sale_type),
     street = factor(street),
      utilities = factor(utilities),
      overall_qual = factor(overall_qual, levels = rev(ten_point)),
      overall_cond = factor(overall_cond, levels = rev(ten_point))
    ) %>%
    mutate(
      pid = ifelse(pid == "0904351040", "0904351045,", pid),
      pid = ifelse(pid == "0535300120", "0535300125,", pid),
      pid = ifelse(pid == "0902401130", "0902401135,", pid),
      pid = ifelse(pid == "0906226090", "0906226090,", pid),
      pid = ifelse(pid == "0908154040", "0908154045,", pid),
      pid = ifelse(pid == "0909129100", "0909129105,", pid),
      pid = ifelse(pid == "0914465040", "0914465043,", pid),
      pid = ifelse(pid == "0902103150", "0902103145,", pid),
      pid = ifelse(pid == "0902401120", "0902401125,", pid),
      pid = ifelse(pid == "0916253320", "0916256880,", pid),
      pid = ifelse(pid == "0916477060", "0916477065,", pid),
      pid = ifelse(pid == "0916325040", "0916325045,", pid)
    ) %>%
    # dplyr::inner_join(ames_geo_modif, by = "pid") %>%
    # Garage_Yr_Blt is removed due to a fair amount of missing data
    dplyr::select(#-order,-pid, 
                  -garage_yr_blt) %>%
    dplyr::mutate(
      neighborhood = factor(neighborhood)
    )


```

```{r}
%>% 
  janitor::clean_names() %>% 
  dplyr::rename(
    pid = MapRefNo
  )
```

